[package]
name = "blog-client"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4"
actix-cors = "0.6"
actix-service = "2"
async-trait = "0.1"
argon2 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
jsonwebtoken = "9"
once_cell = "1"
rand_core = { version = "0.6", features = ["getrandom"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "macros"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono", "time"] }
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1"
futures-util = "0.3"
tonic = { version = "0.14" }
prost = "0.14"
tonic-prost = "0.14"
prost-types = {version = "0.14", features = ["std", "chrono"]}

[build-dependencies]
tonic-prost-build = "0.14"
