[application]
tailwind_input = "tailwind.css"
tailwind_output = "assets/tailwind.css"

[web.app]

# HTML title tag content
title = "blog-wasm"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


